<?php /** @var \Darken\Code\Runtime $this Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

use Darken\Attributes\ConstructorParam;
use Darken\Attributes\Inject;
use MyExtension\MyExtensionConfig;
$example = new class($this)
{
    protected \Darken\Code\Runtime $runtime;
    #[ConstructorParam]
    public string $param;
    #[Inject]
    public MyExtensionConfig $extConfig;
    public function __construct(\Darken\Code\Runtime $runtime)
    {
        $this->runtime = $runtime;
        $this->param = $this->runtime->getData('constructorParams', 'param');
        $this->extConfig = $this->runtime->getContainer(\MyExtension\MyExtensionConfig::class);
    }
};
?>
<div style="padding: 20px; background-color: green; color:white; border-radius: 20px;">
    <?php 
echo $example->param;
?>
    <hr />
    <?php 
echo $example->extConfig->getUcFirstRequiredTestParam();
?>
</div>