<?php /** Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

namespace MyExtension\Build\Components;

class ExampleComponent extends \Darken\Code\Runtime
{
    public function __construct(string $param)
    {
        $this->setData('constructorParams', 'param', $param);
    }
    public function renderFilePath(): string
    {
        return dirname(__FILE__) . DIRECTORY_SEPARATOR . 'ExampleComponent.compiled.php';
    }
}